### PR TITLE
Validate sale price field to only include numbers

### LINKED ISSUE #137: Input price shouldn't accept letters, only numbers
**Describe the bug**
Input price is accepting letters

**To Reproduce**
1. Go to Shop
2. Click on 'Create an offer
3. Go to Price input
4. Type letters
5. See the error

**Expected behavior**
Only accept numbers

**Screenshots**
inputNumber

**Cambiatus Env you are using**
app.cambiatus.io

### PR DESCRIPTION
**Pull request by RodrigoLeiteF**
Closes #137 

Before updating the model we check every character in the sale price and filter out the non-digit ones.

### CODE REVIEW

File: src/elm/Page/Shop/Editor.elm [hunk 1]
```diff
@@ -1148,6 +1148,15 @@ encodeUpdateForm sale form =
         ]
 
 
+getNumericValues : String -> String
+getNumericValues value =
+    value
+        |> String.toList
+        |> List.filter (\x -> Char.isDigit x)
```
Comment (lucca65) [inline src/elm/Page/Shop/Editor.elm]: No need to send a function, you can curry it:

```
|> List.filter Char.isDigit
```

Comment (RodrigoLeiteF) [reply src/elm/Page/Shop/Editor.elm]: Good catch. Fixed
