### PR TITLE
Fix routes restriction based on hasShop and hasObjecitveves community features

### LINKED ISSUE #348: withFeature route fails
**Describe the bug**
In MUDA, some users are unable to open certain pages, that they were able to before

**To Reproduce**
1. Go to https://muda.cambiatus.io (or open localhost pointing to MUDA)
2. Access this path: `/community/MUDA/objectives/6/action/13/claim/1786`
3. See error

**Expected behavior**
This link should work as it is a valid claim link. 

**Screenshots**
Screenshot sent on the bug report, we can see clearly that it was accessible at some point

WhatsApp Image 2020-08-28 at 18 32 49

**Cambiatus Env you are using**
https://muda.cambiatus.io/community/MUDA/objectives/6/action/13/claim/1786

**Desktop (please complete the following information):**
Happens on all desktop devices

**Smartphone (please complete the following information):**
Happens on all smartphone devices

**Additional context**
I did a little digging on this, and found out that the reason it don't work is because of [this function](https://github.com/cambiatus/frontend/blob/cd9d8e0e29c295ce92ae49fe1841fde90bf70337/src/elm/Main.elm#L625-L633). It works fine if I open the link using the `ClickedLink` Msg, but it won't work if we put the URL directly.

Removing this function makes the direct link work again, but then the `withFeature` filter don't work anymore.

### PR DESCRIPTION
**Pull request by amiskov**
## What issue does this PR close
Closes #348 

## Changes Proposed ( a list of new changes introduced by this PR)
Replace `withFeature` function from `Main.elm` with more explicit feature checking. Make sure we have `hasShop` and `hasObjectives` loaded before the actual checking if the page was reloaded by hand.

## How to test ( a list of instructions on how to test this PR)
- Make sure you have `hasShop` enabled. These routes should load correctly by the URL
(try to reload the page with `Cmd/Ctrl+R`):
    + `Shop`,
    + `NewSale`,
    + `EditSale`,
    + `ViewSale`.
- Then disable `hasShop` and make sure that these pages are not available.
- With `hasObjectives` enabled these routes should load correctly by the URL:
    + `Claim`,
    + `EditAction`,
    + `NewAction`,
    + `EditObjective`,
    + `NewObjective`,
    + `Objectives`.
- With `hasObjectives` disabled these pages should be disabled.

### CODE REVIEW

File: src/elm/Page/Community/ActionEditor.elm [hunk 1]
```diff
@@ -1108,7 +1108,18 @@ view ({ shared } as loggedIn) model =
                     Page.fullPageNotFound "not authorized" ""
     in
     { title = title
-    , content = content
+    , content =
```
Comment (lucca65) [inline src/elm/Page/Community/ActionEditor.elm:1111]: nice! i'm glad we changed this structure a while back

**Review by lucca65 — APPROVED** [review]
amazing! did the tests and everything is working as it should!! 

i'm happy to see the improvements and bugs getting fixed 

🔥🔥
