### PR TITLE
Fixes edit offer button styling

### LINKED ISSUE #131: Some buttons do not grow along with the text size
**Describe the bug**
Some buttons do not grow along with the text size

**To Reproduce**
1. Go to Shop
2. Click on My Offers tab
3. Click on Your offer

**Expected behavior**
Buttons size must grow along with the text size. The button must have a padding of at least 16px from the right and left

**Screenshots**
Captura de Tela 2020-01-22 às 10 26 20

**Cambiatus Env you are using**
app.cambiatus.io

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version ???

**Additional context**
Figma url:
https://www.figma.com/file/qyeWaokbgB7xSNSFMaceYZ/Buttons?node-id=0%3A1

### PR DESCRIPTION
**Pull request by victorgdev**
## What issue does this PR close
Closes #131 

## Changes Proposed ( a list of new changes introduced by this PR)
Fixes the following styles of the edit-offer-button:
- Padding (left and right = 16px)
- Sizing (responsive - mobile = full width / desktop = regular size)

## How to test ( a list of instructions on how to test this PR)
1. Go to Shop
2. Click on My Offers tab
3. Click on Your offer
4. Change the viewport size 

## Screenshots of the testing

Mobile
image

Desktop
image

### CODE REVIEW

File: src/elm/Page/Shop/Viewer.elm [hunk 1]
```diff
@@ -448,11 +448,11 @@ viewCard ({ shared } as loggedIn) card model =
                             [ text (tr "account.my_wallet.your_current_balance" [ ( "balance", currBalance ) ]) ]
                         ]
                     ]
-                , div [ class " mt-6 md:mt-0" ]
+                , div [ class " mt-6 md:mt-0 w-full md:w-40 lg:w-40" ]
```
Comment (amiskov) [inline src/elm/Page/Shop/Viewer.elm:451]: `md:w-40` works for 768px and above, so we don't need `lg:w-40` here.

Also, it would be nice to remove that extra space at the beginning of the class string.

**Comment by lucca65** [comment]
ping @victorgdev

File: src/elm/Page/Shop/Viewer.elm (hunk 1 above)
Comment (victorgdev) [reply src/elm/Page/Shop/Viewer.elm:451]: Ok @amiskov sorry for the delay I'll make the changes right now.

Comment (amiskov) [reply src/elm/Page/Shop/Viewer.elm:451]: It looks like you're still in progress on this (maybe need to push changes to github?). Please, re-request review when it's ready.

**Comment by victorgdev** [comment]
> Does not 100% width yet:
> 
> Screen Shot 2020-07-11 at 09 58 18

Hi @heltonlr here is the change in both offer pages. Tks!

image

**Comment by heltonlr** [comment]
Awesome @victorgdev 🤟

**Comment by lucca65** [comment]
Congrats @victorgdev!
