### PR TITLE
Fix/back button

### LINKED ISSUE #520: The back doesn't actually go back
**Describe the bug**
The app contains several different "back" buttons but none of them actually go back, instead they are hard coded to go to a certain page. This makes stuff confusing 

**To Reproduce**
A simple example:

1. Go to the community settings page of a community you are admin of
2. Click on "objectives and actions"
2. Click on "back"
3. See error

**Expected behavior**
Simply go back to same page as it would if we pressed the browser's back button

**Screenshots**
N/A

**Cambiatus Env you are using**
All

### PR DESCRIPTION
**Pull request by NeoVier**
## What issue does this PR close
Closes #520 

## Changes Proposed ( a list of new changes introduced by this PR)
Make the back button always go to the previous page the user was in. If there is no previous page, just go to the dashboard

## How to test ( a list of instructions on how to test this PR)
Go to pages that have the back button and see if it redirects you to the correct page. Make sure you don't fall into a loop. Here is an example navigation that could cause a loop, but shouldn't:

1. Go to `/dashboard`
2. Click on the cog icon on the top right - you'll be redirected to `/community/settings`
3. Click on the "Edit" button under "Objectives and Actions" - you'll be redirected to `/community/objectives`
4. Click the back button - you'll be redirected back to `/community/settings`
5. Click the back button again - you should be redirected back to `/dashboard`

### CODE REVIEW

File: src/elm/Page.elm [hunk 1]
```diff
@@ -254,13 +254,17 @@ viewTitle text_ =
...
     div [ class "w-full h-16 flex px-4 items-center bg-indigo-500" ]
         [ div [ class "flex container mx-auto" ]
             [ a
                 [ class "flex items-center mr-4"
-                , Route.href route
+                , routeHistory
+                    |> List.drop 1
+                    |> List.head
+                    |> Maybe.withDefault Route.Dashboard
+                    |> Route.href
```
Comment (lucca65) [inline src/elm/Page.elm:267]: ohhhhh I never figured out how we would know this, dumb me it's simply a list 🤡

**Review by lucca65 — APPROVED** [review]
🔥🔥🔥🔥🔥

File: src/elm/Page.elm (hunk 1 above)
Comment (NeoVier) [reply src/elm/Page.elm:267]: To be fair, it took some trial and error to get it right and avoid any loops :laughing:
