### PR TITLE
Fix action form creation elements' styling

### LINKED ISSUE #175: Several wrong elements in the editing and action creation forms
**Describe the bug**
Several wrong elements in the editing and action creation forms:

- Checkbox
- Inputs
- Text alignment
- Toogle

Screen Shot 2020-02-18 at 12 24 07

**To Reproduce**
1. Click on explore
2. Click on edit
3. Click on edit action

**Expected behavior**

**Cambiatus Env you are using**
app.cambiatus.io

**Smartphone (please complete the following information):**
 - Device: Xiaomi
 - OS: Android
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by victorgdev**
## What issue does this PR close
Closes #175 

## Changes Proposed ( a list of new changes introduced by this PR)
All changes were based of the figma form elements. Below is the list of items changes requested:

- Toggle element sizing and look
- Checkbox styling 
- Text left alignment 
- Input fields sizing on mobile experience

## How to test ( a list of instructions on how to test this PR)
Changing screen size

## Print Screens
**Desktop**
print3

**Mobile**
print4
print2

### CODE REVIEW

File: src/elm/Page/Community/ActionEditor.elm [hunk 1]
```diff
@@ -1164,10 +1164,10 @@ viewDescription { shared } form =
             text (t shared.translations s)
     in
     div [ class "mb-10" ]
-        [ span [ class "input-label" ]
+        [ span [ class "input-label flex" ]
             [ text_ "community.actions.form.description_label" ]
         , textarea
-            [ class "w-full input rounded-sm"
+            [ class "input rounded-sm w-2/5 sm-max:w-full md-max:w-full"
```
Comment (amiskov) [inline src/elm/Page/Community/ActionEditor.elm:1170]: If I understand it right, the purpose of `w-2/5 sm-max:w-full md-max:w-full` is to make `textarea` full-width up to middle screens (768px) and then make it `w-2/5`. For such behavior in Tailwind it's better to use [mobile-first approach](https://tailwindcss.com/docs/responsive-design/#mobile-first): start with mobile style and then add changes for bigger screens, like this:

```
class "input rounded-sm w-full md:w-2/5"
```

File: src/elm/Page/Community/ActionEditor.elm [hunk 2]
```diff
@@ -1164,10 +1164,10 @@ viewDescription { shared } form =
             text (t shared.translations s)
     in
     div [ class "mb-10" ]
-        [ span [ class "input-label" ]
+        [ span [ class "input-label flex" ]
```
Comment (amiskov) [inline src/elm/Page/Community/ActionEditor.elm:1167]: Why do we need `flex` here?

File: src/elm/Page/Community/ActionEditor.elm [hunk 3]
```diff
@@ -1187,7 +1187,7 @@ viewReward { shared } community form =
     div [ class "mb-10" ]
         [ span [ class "input-label" ]
             [ text_ "community.actions.form.reward_label" ]
-        , div [ class "flex sm:w-2/5 h-12 rounded-sm border border-gray-500" ]
+        , div [ class "flex w-2/5 sm-max:w-full md-max:w-full h-12 rounded-sm border border-gray-500" ]
```
Comment (amiskov) [inline src/elm/Page/Community/ActionEditor.elm:1190]: Same tip with mobile first here. This class could be simpler:

```
class "flex w-full md:w-2/5 h-12 rounded-sm border border-gray-500"
```

File: src/elm/Page/Community/ActionEditor.elm [hunk 4]
```diff
@@ -1232,18 +1232,20 @@ viewValidations { shared } model =
                         , label [ class "form-switch-label", for "expiration-toggle" ] []
                         ]
                     , label [ class "flex text-body text-green", for "expiration-toggle" ]
-                        [ p [ class "font-bold mr-1" ]
-                            [ if model.form.validation == NoValidation then
-                                text_ "community.actions.form.validation_off"
+                        [ p [ class "mr-1" ] 
+                            [ Html.b []
```
Comment (amiskov) [inline src/elm/Page/Community/ActionEditor.elm:1236]: I think it's better to use just `b` since all other tags have no `Html.` prefix. You can add `b` in the `exposing` list in the line `36`.

File: src/elm/Page/Community/ActionEditor.elm [hunk 5]
```diff
@@ -1273,15 +1277,15 @@ viewValidations { shared } model =
...
+                                [ span [ class "input-label " ]
                                     [ text_ "community.actions.form.date_label" ]
                                 , div [ class "mb-10" ]
                                     [ MaskedDate.input
                                         { dateOptions
                                             | pattern = "##/##/####"
                                             , inputCharacter = '#'
                                         }
-                                        [ class "input"
+                                        [ class "input w-2/5 sm-max:w-full md-max:w-full"
```
Comment (amiskov) [inline src/elm/Page/Community/ActionEditor.elm:1288]: Another place for using the mobile-first approach.

File: src/elm/Page/Community/ActionEditor.elm [hunk 6]
```diff
@@ -1429,7 +1442,7 @@ viewManualVerificationForm ({ shared } as loggedIn) model community =
             text ""
 
         Manual selectedVerifiers verificationReward minVotes ->
-            div [ class "w-2/5" ]
+            div [ class "elm-selected-verifiers mt-6 w-2/5 sm-max:w-full md-max:w-full" ]
```
Comment (amiskov) [inline src/elm/Page/Community/ActionEditor.elm:1445]: `elm-selected-verifiers` seems to be unnecessary.

File: src/styles/main.css [hunk 7]
```diff
@@ -249,7 +250,22 @@
...
+  height: 20px;
+  border: 1px solid #e7e7e7;
+  border-radius: 2px;
+}
+
+#date:checked, 
+#quantity:checked {
+  background: white;
+  border: 6px solid #8acc9e;
+  border-radius: 2px;
```
Comment (amiskov) [inline src/styles/main.css:268]: The issue with checkboxes is not only related to these fields, it's site-wide. We are using [Tailwind Custom Form](https://tailwindcss-custom-forms.netlify.app/) and the `.form-checkbox` class is provided by it. We have some customization in `tailwind.config.js:11` but it looks like it's not enough...

File: tailwind.config.js [hunk 8]
```diff
@@ -135,6 +135,12 @@ module.exports = {
       },
       opacity: {
         '10': '0.1'
+      },
+      screens: {
+        'sm-max': { 'max': '639px' },
+        'md-max': { 'max': '767px' },
+        'lg-max': { 'max': '1023px' },
+        'xl-max': { 'max': '1279px' }
```
Comment (amiskov) [inline tailwind.config.js:143]: Do we really need these breakpoints? Maybe if my suggestions about mobile-first approach will work fine we could keep things simple and use what we already have?

File: src/elm/Page/Community/ActionEditor.elm (hunk 1 above)
Comment (lucca65) [reply src/elm/Page/Community/ActionEditor.elm:1170]: +1 to taking a time to learn more about the way tailwind structures itself. The video series is simple, beginner friendly: https://tailwindcss.com/course/responsive-design

**Comment by lucca65** [comment]
any news on this PR @victorgdev?

**Comment by victorgdev** [comment]
> There are some comments. Feel free to ping me in Slack if you'll have questions!
> 
> The Elm code is not formatted properly. Please, use [`elm-format`](https://github.com/avh4/elm-format) in your editor. I guess there are plugins for any of them. It's good to run it on file save.

Thanks @amiskov I will.

File: src/elm/Page/Community/ActionEditor.elm (hunk 1 above)
Comment (victorgdev) [reply src/elm/Page/Community/ActionEditor.elm:1170]: Sorry for the delay in responding and thanks for the review and tip!

File: tailwind.config.js (hunk 8 above)
Comment (victorgdev) [reply tailwind.config.js:143]: Absolutely not! The mobile-first worked perfectly! I will take it off!

**Comment by victorgdev** [comment]
> any news on this PR @victorgdev?

@lucca65 requested changes were sent for new review earlier today. Sorry for delayed response!

File: tailwind.config.js [hunk 9]
```diff
@@ -10,7 +10,7 @@ module.exports = {
       default: {
         checkbox: {
           icon:
-            '<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="12" height="12" rx="2" fill="#8ACC9E"/></svg>'
+            '<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="12" height="12" rx="2" fill="#ffffff"/></svg>'
```
Comment (amiskov) [inline tailwind.config.js:13]: That's how checked checkbox represented in the [Figma mock-up](https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=590%3A216):
image
That's how it looks in the browser:
image
There should be a green square in the middle of the grey square, not the opposite. BTW the same is for the radio button. It looks like we just messed the styles a bit...

To achieve this behaviour you can try something like this in `tailwind.config.js` around line 11:

```js
checkbox: {
  width: theme('spacing.6'),
  height: theme('spacing.6'),
  icon: '<svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">' +
    '<rect x="0.5" y="0.5" width="21" height="21" rx="2.5" fill="white" stroke="#E7E7E7"/>' +
    '<rect x="5" y="5" width="12" height="12" rx="2" fill="#8ACC9E"/>' +
    '</svg>'
},
radio: {
  width: theme('spacing.6'),
  height: theme('spacing.6'),
  icon: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">' +
    '<circle cx="12" cy="12" r="11.5" fill="white" stroke="#E7E7E7"/>' +
    '<path d="M18 12C18 15.3137 15.3137 18 12 18C8.68629 18 6 15.3137 6 12C6 8.68629 8.68629 6 12 6C15.3137 6 18 8.68629 18 12Z" fill="#8ACC9E"/>' +
    '</svg>'
}
```

I exported the SVGs from Figma. And used them in the Tailwind Custom Forms config, [here](https://tailwindcss-custom-forms.netlify.app/)'s the documentation.

File: src/styles/main.css [hunk 10]
```diff
@@ -249,7 +250,17 @@
...
+}
+
+.form-checkbox {
+  @apply w-5 h-5 border border-solid border-gray-500 rounded-sm bg-white;
+   
+}
+
+.form-checkbox:checked {
+  @apply w-5 h-5 border-4 border-solid border-green rounded-xs bg-white;
+
```
Comment (amiskov) [inline src/styles/main.css:263]: The changes for `tailwind.config.js` I suggested in the comment below will work fine then we don't need `.form-checkbox` classes at all. Although, I may be wrong, please, check how it will work.

File: src/elm/Page/Community/ActionEditor.elm [hunk 11]
```diff
@@ -1295,16 +1298,17 @@ viewValidations { shared } model =
                             text ""
             , div [ class "mb-6 flex flex-row text-body items-bottom" ]
                 [ input
-                    [ id "quantity"
-                    , type_ "checkbox"
+                    [ type_ "checkbox"
```
[the remark this answers is not in the document]
Comment (victorgdev) [reply src/elm/Page/Community/ActionEditor.elm:1301]: Sorry, I could swear I created them to give them css rules. I will revert it!

File: tailwind.config.js (hunk 9 above)
Comment (victorgdev) [reply tailwind.config.js:13]: Hi @amiskov, I spoke with Helton about the style of the button because the figma style (green fill and "white" border) causes an effect of being a smaller square due to the page's background color. He told me to use the other way around.

File: src/styles/main.css (hunk 10 above)
Comment (victorgdev) [reply src/styles/main.css:263]: Nice! I will check it out!

File: tailwind.config.js (hunk 9 above)
Comment (lucca65) [reply tailwind.config.js:13]: Hmmm, this should be updated on Figma then, or at least be spoken of in #ux-ui so everyone knows what's going on. We should expect communication problems to happen as we grow larger. 

@heltonlr can you please update the Figma designs?

And for everyone else, please lets try to discuss design stuff that don't make sense in shared channels so we have a way to avoid situations like this

Comment (heltonlr) [reply tailwind.config.js:13]: Sorry, I'll write in Portuguese so I don't have any doubts:

@victorgdev , acho que eu te expliquei errado. O checkbox continua como está, com o quadrado verde indicando que o mesmo está selecionado. Já a borda em cinza é que podemos escurecer para aparecer melhor no background daquela página. Se quiser, me liga para esclarecer melhor essa questão. Desculpa qualquer confusão.

**Comment by heltonlr** [comment]
Hey @victorgdev and @lucca65 sorry for my communication failure,

The correct border is **#E7E7E7**
All the forms in the app must have a white background (**#FFFFFF**). Let me know if that is the problem, if the background have the same colour of the checkbox's border.

**On this example there are all checkbox that we use:**
https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=1528%3A13

File: tailwind.config.js (hunk 9 above)
Comment (victorgdev) [reply tailwind.config.js:13]: @heltonlr sorry for the miscommunication and I will revert the configurations of the checkbox! Thanks!

**Comment by victorgdev** [comment]
Hi @heltonlr, can you check if there any other changes to be done with this PR or if we are all set for implementation? Tks!

**Comment by heltonlr** [comment]
Looks good to me
