### PR TITLE
Fix/muda workshop live fixes

### LINKED ISSUE #71: Language suddenly changes
**Describe the bug**
For various users, the language changes out of the blue, mainly to CAT. They get really confused. 

**Expected behavior**
Language changes suddenly 

**Screenshots**

**Cambiatus Env you are using**
cambiatus.borboins.io

### LINKED ISSUE #73: Session finished automatically but it was still on in the background (odd behaviour)
**Describe the bug**

An user was logged and doing a claim. When he was going to complete the claim, his session was finished automatically and requested to log in again. however if he tap the back button, his session was still on, but when trying to claim again, he will be requested to log in again (including PK). 

**Expected behavior**
As explained 

**Screenshots**

**Cambiatus Env you are using**
borboins..cambiatus.io

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - OS: 
 - Browser : Chrome 
 - Version 77.0.3865.116

### LINKED ISSUE #75: Session automatically finished whilst doing a transfer
**Describe the bug**
Session automatically finished whilst doing a transfer

**Cambiatus Env you are using**
borboins.cambiatus.io

**Smartphone (please complete the following information):**
 - Device: Xiaomi A1N1
 - OS: 
 - Browser Mozilla Firefox
 - Version 68.1.1

**Additional context**
Ranulfo's phone

### PR DESCRIPTION
**Pull request by lucca65**
Big PR with several fixes and quality improvements:

- No longer do hygiene on the PIN input. Instead let it fail to be validated. Done on Register and Login
- Add type signature to some functions on `Icons.elm` file
- Redo language buttons logic. Now it will always be sorted alphabetically and will show the current language on top
- Fix profile image load during login (a wrong param in decoding made it not load on login, only on new page refresh)
- Adjust Cambiatus logo in both guest and logged in pages.
- Major refactor on the menu items:
  - Now it closes with Escape key (Esc)
  - Updated design
  - Now it closes when you click outside of the menu
  - No more misclicks due to z-index
  - Add darker background around the items so it is easier to show
  - As specified by @heltonlr the menu now opens on mouse hover

This PR: 
fixes #71
fixes #75
fixes #89
fixes #73

Note: I'm guessing the logouts happened due to the z-index bug, that is there was a hidden menu that was still clickable, and in the mobile the logout button stayed behind the transfer button. Those issues may be reopened if needed but I've tested it and I'm confident it will solve those issues

### CODE REVIEW

File: src/elm/Auth.elm [hunk 1]
```diff
@@ -789,66 +787,38 @@ update msg shared model =
             loginFailed err model
 
         EnteredPinDigit pos data ->
-            {- 96 to 105 is 0-9 from numerical keyboard.
```
Comment (zacck) [inline src/elm/Auth.elm]: @lucca65  this was always a valiant effort bro
